/** @type {import('tailwindcss').Config} */

// Generated by https://www.tints.dev/

module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#E6E9EF',
          100: '#CDD3DF',
          200: '#9BA6C0',
          300: '#6D7DA2',
          400: '#495673',
          500: '#2A3142',
          600: '#222835',
          700: '#1A1E29',
          800: '#101319',
          900: '#08090C'
        },
        onPrimary: {
          50: '#FCFCFD',
          100: '#F9FAFB',
          200: '#F3F4F6',
          300: '#EDEFF2',
          400: '#E8EAEE',
          500: '#E0E3E8',
          600: '#ADB5C2',
          700: '#78859B',
          800: '#4E5869',
          900: '#272C35'
        },
        secondary: {
          50: '#FBF9EE',
          100: '#F8F4DE',
          200: '#F0E9BC',
          300: '#E9DD9B',
          400: '#E2D279',
          500: '#DBC75A',
          600: '#C9B12C',
          700: '#978521',
          800: '#645916',
          900: '#322C0B'
        },
        tertiary: {
          50: '#F1F4FE',
          100: '#E3EAFC',
          200: '#C7D5FA',
          300: '#ABBFF7',
          400: '#8FAAF5',
          500: '#7295F2',
          600: '#3263EC',
          700: '#1242C4',
          800: '#0C2C83',
          900: '#061641'
        }
      }
    }
  },
  plugins: []
}
